### ISSUE TITLE
A couple of questions/issues

### ISSUE THREAD

**Issue by gosoccerboy5** [Chiroyce1/tfh-form#1]
```
[START of application]
@gosoccerboy5 - active in Suggestions, Advanced Topics, Questions about Scratch.
Most constructive posts - foo, bar, baz, .
Most recent post: hello.
Additional info: goodbye.
[END of application]
```
Not bad. It seems to fit under the post limit mostly, however if an applicant used 4 post links and used the long version ("https://scratch.mit.edu/discuss/topic/617869/?page=1#post-6455412") it might go over the 500 limit.

I'm just confused - is the "[START of application]" and "[END of application]" necessary?

**Comment by gosoccerboy5** [comment]
Additionally if you look at the form above, after "foo, bar, baz" there's an extra comma.
After line 29 in script.js you should add `posts = posts.filter(post => post !== "");` so you're not appending any empty values that weren't filled in.

**Comment by Chiroyce1** [comment]
> I'm just confused - is the "[START of application]" and "[END of application]" necessary?

was there for debugging purposes. will be removed.

> Additionally if you look at the form above, after "foo, bar, baz" there's an extra comma. After line 29 in script.js you should add `posts = posts.filter(post => post !== "");` so you're not appending any empty values that weren't filled in.

will do that. i'll also add in a `post.trim()` to make sure white space isnt detected

> Additionally, if you're looking to save post space - you can run this on the post links they provide to save space:
> 
> ```js
> function betterPostLink(link) {
>   return link.replace(/topic\/\d+\/\?page=\d#post-/, "post/");
> }
> alert(betterPostLink("https://scratch.mit.edu/discuss/topic/343602/?page=1#post-3466932"));
> ```
> 
> 😁

thank you!! will add this soon.

**Comment by gosoccerboy5** [comment]
😁

**Comment by Chiroyce1** [comment]
> Additionally if you look at the form above, after "foo, bar, baz" there's an extra comma.

@gosoccerboy5 with the current implementation itself, I cannot replicate this
```
@griffpatch - active in Suggestions, Advanced Topics, Questions about Scratch.
Most constructive posts - number1, number2, number3, number4.
Most recent post: https://scratch.mit.edu/discuss/12345.
Additional info: codeword is scratch. 
```
Are you sure you haven't manually added an extra comma?

**Comment by gosoccerboy5** [comment]
> 

no, this happens only when not all the post forms are filled out. it still counts the value of the empty text box

**Comment by Chiroyce1** [comment]
> no, this happens only when not all the post forms are filled out. it still counts the value of the empty text box

i see, thanks. ive implemented your changes, so lmk what you think.

**Comment by gosoccerboy5** [comment]
Great! One little thing, maybe call the `betterPostLink` on the "most recent post" part?

**Comment by Chiroyce1** [comment]
@gosoccerboy5 done, also if you want you can PR and add the ScratchDB verification part if you're interested.

**Comment by gosoccerboy5** [comment]
(I haven't coded in a while bc im lazy so this is exciting)

**Comment by Chiroyce1** [comment]
> That sounds fun! What's the sdb verification part?

So we have an array of subforums, we need to make sure all the posts the user has provided in the constructive section falls in any of those, otherwise prevent them from creating the application and let them know that the post will not be accepted. And also go through the user's post count and make sure they have more than 500 posts. I think this much should be enough for now.

> (I haven't coded in a while bc im lazy so this is exciting)

LOL I asked if you wanted to do it since i was lazy too 😛

**Comment by gosoccerboy5** [comment]
also check that the posts are theirs

also do you need a part on the codeword? just reminding users that they need the codeword as well?

**Comment by Chiroyce1** [comment]
> also do you need a part on the codeword? just reminding users that they need the codeword as well?

nope, they're meant to include it in the additional info section as leahcimto suggested here - https://github.com/theforumhelpers/theforumhelpers.github.io/issues/309#issuecomment-1186312748

> also check that the posts are theirs

cool idea too lol

**Comment by webdev03** [comment]
The ScratchDB part could just be webscraper that goes to the URL and checks the subforum, it would update fast so no need for ScratchDB too? This might be possible to do on client side too.
```js
document.querySelector(".linkst ul > li:nth-child(2) a").innerText
```
Could work?

**Comment by gosoccerboy5** [comment]
you don't need a webscraper. just fetch the post from scratchdb and that gives you data like which subforum and who posted it

**Comment by gosoccerboy5** [comment]
fetch works with scratchdb.

**Comment by webdev03** [comment]
Oh, sorry I didn't know about that.

**Comment by gosoccerboy5** [comment]
But you might be right about the sdb being down comment. Btw, I have a fork of this repository if you wanna check that out.

**Comment by gosoccerboy5** [comment]
but scratchdb is open to all requests so cors isn't an issue for scratchdb

**Comment by Chiroyce1** [comment]
> but scratchdb is open to all requests so cors isn't an issue for scratchdb

yeah im sure that webdev03 was talking about fetching directly from scratch

**Comment by gosoccerboy5** [comment]
hey @Chiroyce1 can we talk on discord

**Comment by webdev03** [comment]
Weird... it was working earlier.. now it is giving CORS error. ScratchDB would be easier then. Sorry for wasting your time.
